### ISSUE TITLE
Code of Player Control

### ISSUE THREAD

**Issue by Tat5ato** [Tat5ato/Phantasmic-Mind#1]
All we need is the basic WASD control for the player and the control does not have to be restricted on a grid system

**Comment by Tat5ato** [comment]
This is currently being done Vance Winstead

**Comment by vwinstea** [comment]
Mostly done and uploaded

**Comment by hecker-man** [comment]
until mon oct 2

**Comment by Tat5ato** [comment]
Be sure to add rigidbody and change gravity to 0. Also add the box collider at feet

**Comment by Tat5ato** [comment]
Also lock rotation along the z axis to stop it from spinning. Its in the constraint section of the rigidbody
