### ISSUE TITLE
Music for  Level 1

### ISSUE THREAD

**Issue by Tat5ato** [Tat5ato/Phantasmic-Mind#10]
This is more a debate topic for the musicians and I later since I debating what form of music is best at creating atmosphere. Since we're going for a Silent Hills like background music, 8-64 bit may not cut it, but it fits the game style, while a more realistic piece does much of the opposite: fitting for atmosphere, but not style.

**Comment by Tat5ato** [comment]
Go ham with the music, make as many as we wish as long as it fits the nuances

**Comment by AndrewGalusha** [comment]
Maybe we can try something like this https://www.youtube.com/watch?v=jXjDMERR08c (From The Last of Us)

**Comment by AndrewGalusha** [comment]
We have 4 sound tracks currently, do you guys think that's plenty for just level 1 currently? I'll close this for now unless I hear otherwise.
