### ISSUE TITLE
Code for Player Health

### ISSUE THREAD

**Issue by Tat5ato** [Tat5ato/Phantasmic-Mind#2]
Nothing fancy, just need the standard 100% health that'll scale down from being hit by damage.

**Comment by Tat5ato** [comment]
This is done by Jacob Cunningham

**Comment by hecker-man** [comment]
oct 9

**Comment by hecker-man** [comment]
Issue can only be closed along with a reference to the file.

**Comment by BenKrueger02** [comment]
Srujan closed it today, because he said he did it. He just closed it on my
computer.
