### ISSUE TITLE
Henry Footsteps

### ISSUE THREAD

**Issue by hecker-man** [Tat5ato/Phantasmic-Mind#24]
oct 9

**Comment by AndrewGalusha** [comment]
I know it's closed currently but I'm gonna see what I can do about this sound Efx, I might be able to improve it significantly.

**Comment by AndrewGalusha** [comment]
Here's a link to the footsteps I made, https://soundcloud.com/user-440644275/footsteps and https://soundcloud.com/user-440644275/footsteps-outdoorswalking, I'll be adding more as I make them today.
Also would this work in the cave? There's a bit of trouble on getting the right solid sound for walking on rocks so maybe we can just cover the cave floor with a bit of overgrowth

**Comment by AndrewGalusha** [comment]
Here's for when you are running/sprinting https://soundcloud.com/user-440644275/footsteps-outdoorsrunning, should I add these to the main project?
