### ISSUE TITLE
Echoing Water Drops

### ISSUE THREAD

**Issue by hecker-man** [Tat5ato/Phantasmic-Mind#27]

**Comment by hecker-man** [comment]
Oct 12

**Comment by asgalusha** [comment]
Here's the link to some rain effects I did for indoor scenarios. [https://soundcloud.com/user-440644275/rain-effects-indoors](url)

**Comment by AndrewGalusha** [comment]
Here's the link to some rain effects I did for indoor scenarios: https://soundcloud.com/user-440644275/rain-effects-indoors

**Comment by asgalusha** [comment]
Here's cave water drops version 1 and 2, I can create more versions but really only if we would need them
https://soundcloud.com/user-440644275/cave-water-drops-1
https://soundcloud.com/user-440644275/cave-water-drops-2

**Comment by AndrewGalusha** [comment]
I have the water drops completed (https://soundcloud.com/user-440644275/cave-background), should I add this to the sound folder we have here on GitHub?
