### ISSUE TITLE
Code for Fear Gauge

### ISSUE THREAD

**Issue by Tat5ato** [Tat5ato/Phantasmic-Mind#3]
The code regarding this one is tricky to thing about as the best solution is to model it after health, but affected by different variables (enemy appearance, new area, etc).

**Comment by liamgolly** [comment]
ima start doing this tell me if i can't for some reason

**Comment by vwinstea** [comment]
Your code is confusing for Henry.cs. Are you coding Henry's stats or his fear gauge?

**Comment by liamgolly** [comment]
I am coding for the fear gauge, and it’s depletion and regeneration in certain conditions.
