### ISSUE TITLE
Health/Sanity Bar, Menu for Inventory

### ISSUE THREAD

**Issue by breezebl0ck** [Tat5ato/Phantasmic-Mind#31]

**Comment by KadenFoley** [comment]
![fear_gauge](https://user-images.githubusercontent.com/27833224/31101706-b5159176-a783-11e7-88f5-bafa1d4fc272.png)

![fear_gauge_bar](https://user-images.githubusercontent.com/27833224/31101709-b6c168ec-a783-11e7-8d8f-4ac2b6f52678.png)

**Comment by KadenFoley** [comment]
![health gauge](https://user-images.githubusercontent.com/27833224/31102717-3c38221e-a788-11e7-8831-551d56681e06.png)

**Comment by KadenFoley** [comment]
![fear](https://user-images.githubusercontent.com/27833224/31103035-b54cf53e-a789-11e7-9a42-c20943ac859b.png)
