### ISSUE TITLE
Code for Menu 

### ISSUE THREAD

**Issue by Tat5ato** [Tat5ato/Phantasmic-Mind#4]
The most important parts of the menu system that I think we should prioritize are pausing, sound control/option menu, and quick saves. We can toggle the menu screen to p for convenience.

**Comment by Tat5ato** [comment]
This is going to be done by Brenton Kearney

**Comment by hecker-man** [comment]
oct 12

**Comment by programmer1up** [comment]
[Phasmatic Mind Menu Test.zip](https://github.com/Tat5ato/Phantasmic-Mind/files/1339361/Phasmatic.Mind.Menu.Test.zip)
