### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by caylaemily** [Tat5ato/Phantasmic-Mind#45]
A website that advertises the game and our team. Use wix.com

**Comment by caylaemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Website](https://trello.com/c/XEZzIt8S/12-website)

**Comment by Descrates** [comment]
I can start working on this, but if we're using wix.com or some other website creation program, we need to pay for our own domain. _"PhantasmicMind.wix.com"_ would look pretty unprofessional.

**Comment by caylaemily** [comment]
We are aware that we would have to pay for our own domain. We would like to have our own, but that is to be discussed with Greenway when it comes to funding. For now, he would like if we would use wix's free plan.

Also, we don't have to create the website on the spot. What I mean by this is, for now, we could just write down what information would be put onto the website (ex. company description, old/present game descriptions etc.) and keep them on a notepad or something like that until we get the whole domain thing situated. Think of it as putting together a rough draft until we are ready to create the final draft.

Btw, the website would be for our company, not the game specifically. It would be "_WireframeCreations.com_".
