### ISSUE TITLE
Game Logic for therapist

### ISSUE THREAD

**Issue by hecker-man** [Tat5ato/Phantasmic-Mind#46]
someone must figure out how game will work with the chosen fears at the beginning of the game.

**Comment by Tat5ato** [comment]
We don't need and can't have the code for it without understanding what are going to be the base fear for the players. It'll be up to the script team before coders

**Comment by Descrates** [comment]
Are we choosing Fears/Fear Resistance(things that you choose to do in the Overworld dictate what you're afraid of in the Underworld) at the beginning of the game?
