### ISSUE TITLE
Storage of consumables

### ISSUE THREAD

**Issue by hecker-man** [Tat5ato/Phantasmic-Mind#48]
Menu for the items that player had. Along with using and adding items to this storage.

**Comment by Kingofweirdos01** [comment]
@cooljoe21 we have @Skipperj7 working on this

**Comment by programmer1up** [comment]
I've created a hotbar system with these features. Graphics are default but the mechanics are done

**Comment by Kingofweirdos01** [comment]
The code for consumables storage is done
