### ISSUE TITLE
Code for Damage/Attack

### ISSUE THREAD

**Issue by Tat5ato** [Tat5ato/Phantasmic-Mind#5]
A lot more work is needed for this too an extent as not only I want the code be for just damage, but also take into consideration to the defense stats of the opponent. To elaborate, some enemies has high defense,  but low HP, so the player's attack as to scale in accordance to the stats of the opponent.

**Comment by Tat5ato** [comment]
Forgot to mention, but the attack can be buff and debuffed if a player uses an item for is penalized by fear/insanity.

**Comment by Kingofweirdos01** [comment]
i will work on this

**Comment by Kingofweirdos01** [comment]
@Tat5ato someone is working on damage i put my health code into github though
