### ISSUE TITLE
Backstory for Iggy

### ISSUE THREAD

**Issue by hecker-man** [Tat5ato/Phantasmic-Mind#53]
We need the backstory to Iggy that has no relationship to Henry's wife.

**Comment by hecker-man** [comment]
Oct 19

**Comment by AndrewGalusha** [comment]
Here's the document to the Lore for the characters if you still have any questions https://docs.google.com/document/d/17vtai41PUWSEouSAE7klxgsX1DKY7WJQpQ0OBCvxJfs/edit
