### ISSUE TITLE
Backstory for Jennifer

### ISSUE THREAD

**Issue by hecker-man** [Tat5ato/Phantasmic-Mind#54]
AKA the man and therapist

**Comment by hecker-man** [comment]
Oct 19

**Comment by Descrates** [comment]
already done: [Character Backstories - Phantasmic Mind](https://docs.google.com/document/d/17vtai41PUWSEouSAE7klxgsX1DKY7WJQpQ0OBCvxJfs/edit?usp=sharingl)

**Comment by Descrates** [comment]
If any questions are left unanswered, see this document: [Lore - Phantasmic Mind](https://docs.google.com/document/d/1CnMmgxVvPggjE0t1REFpCS7e3vT48LtmFnpqEGCNpH4/edit?usp=sharingl)

**Comment by AndrewGalusha** [comment]
If you still have any questions, like Lavi said above, just check out the lore document. Closing this for now unless we need to add onto it.
