### ISSUE TITLE
Code for Item Consumption

### ISSUE THREAD

**Issue by Tat5ato** [Tat5ato/Phantasmic-Mind#6]
The items that had been thought of that the player is going to use are buffs and debuffs. The two affects not only  the player, but also the fear gauge-the alcohol and anti-depressants affects it. As such, it has to call back to the health and fear gauge when used (or some other methods, I'm not too knowledgeable about coding so I don't know how to properly do it).

**Comment by hecker-man** [comment]
oct 12
