### ISSUE TITLE
Monster Sound Effects

### ISSUE THREAD

**Issue by AndrewGalusha** [Tat5ato/Phantasmic-Mind#60]
Sounds that you'd hear when you are near a monster (growls, barks, howls, and so on). Let's see what you can make!

**Comment by AndrewGalusha** [comment]
Link to a simple monster sound effect, don't know exactly what monster could have it but it'd sound strange to hear this in one of our environments: https://soundcloud.com/user-440644275/monsterefx1

**Comment by slendyglowstone** [comment]
Plopped a few in the SFX more to come
