### ISSUE TITLE
Top down cave backgrounds, battle backgrounds 

### ISSUE THREAD

**Issue by breezebl0ck** [Tat5ato/Phantasmic-Mind#62]

**Comment by TheDoritoWisard** [comment]
Due when?

**Comment by Nick1443** [comment]
![evil 128bit by 128bit](https://user-images.githubusercontent.com/32180567/31638837-928960ee-b28a-11e7-8f66-36aa5d7fc36e.png)

**Comment by AndrewGalusha** [comment]
![cavemap1](https://user-images.githubusercontent.com/29155447/31701717-2f4d0b90-b387-11e7-816d-56898f470088.png)
I'm thinking that it should look something like this, however if you are able to recreate this at a higher resolution to fit our characters, that be a lot of help.

**Comment by AndrewGalusha** [comment]
This isn't quite done yet but there is a much more refined post here: https://github.com/Tat5ato/Phantasmic-Mind/issues/65, I'll close this one to clean things up a bit.
