### ISSUE TITLE
Fleshy Text Box And Normal Text Box

### ISSUE THREAD

**Issue by breezebl0ck** [Tat5ato/Phantasmic-Mind#64]

**Comment by TheDoritoWisard** [comment]
Is this for art or code

**Comment by TheDoritoWisard** [comment]
![text box](https://user-images.githubusercontent.com/32028573/32354000-f912a642-bfe4-11e7-8141-2e95977311b2.jpg)

**Comment by TheDoritoWisard** [comment]
Done with regular Text box

**Comment by TheDoritoWisard** [comment]
![flesh text box](https://user-images.githubusercontent.com/32028573/32354356-9b7feb46-bfe6-11e7-9f76-126aea43fe6e.jpg)

**Comment by TheDoritoWisard** [comment]
Done with Flesh Text Box

**Comment by snekmm** [comment]
what should be the dimensions of the text boxes
