### ISSUE TITLE
Concept Art for Enemies

### ISSUE THREAD

**Issue by Tat5ato** [Tat5ato/Phantasmic-Mind#7]
We already have two drafts for the enemies, but I want see more designs from the other artists. What I'm mainly looking for however are three types of designs: a blob looking thing with humanistic quality, a gross monstrosity, and finally something that if you were to see it in real life, it can cause you to go insane.

**Comment by snekmm** [comment]
![spooky 3](https://user-images.githubusercontent.com/32024602/30516560-a054fbe8-9af7-11e7-9acf-ed059c145281.png)

**Comment by asgalusha** [comment]
What kind of resolution should we be doing our concept art in? Like what will the final game be displaying at in pixels? or should we just do any resolution and worry about downscaling later

**Comment by Nick1443** [comment]
![evil](https://user-images.githubusercontent.com/32180567/31101633-80e73e18-a783-11e7-9b33-cb437158fb56.png)

**Comment by Nick1443** [comment]
![evil blob](https://user-images.githubusercontent.com/32180567/31102694-24590514-a788-11e7-8a1a-b6a86cd1f654.png)

**Comment by hecker-man** [comment]
@Nick1443 @snekmm I'm going to assign you guys to different assignments and you guys can also put your art there.
