### ISSUE TITLE
Map (Crude Outline)

### ISSUE THREAD

**Issue by KadenFoley** [Tat5ato/Phantasmic-Mind#72]

**Comment by Tat5ato** [comment]
Leave comments plz

**Comment by KadenFoley** [comment]
![la mapa concepto](https://user-images.githubusercontent.com/27833224/31966586-fdafe448-b8bf-11e7-8b11-a82a6fa9ba45.png)
This is really basic thing for the map dude so he knows where the hell things go, ill do an actual map later

**Comment by AndrewGalusha** [comment]
I think it should be a bit more linear, also do remember that this is in a cave, but good idea on what types of tutorials we should have.

**Comment by AndrewGalusha** [comment]
![map outline](https://user-images.githubusercontent.com/29155447/31981381-c0fcf11a-b907-11e7-8321-e6336b511eba.jpg)
