### ISSUE TITLE
Tile Art Needed For Level 1

### ISSUE THREAD

**Issue by AndrewGalusha** [Tat5ato/Phantasmic-Mind#73]
Just some basic tiles are needed, such as multiple forms of stone, boulders, rock walls, maybe water (both running and stationary) and so on. Our characters our in 64x64 resolution so let's work with that resolution unless something else comes along.

**Comment by KadenFoley** [comment]
Official Say on this assignment: No specific resolution requirement, but must follow the color scheme.

Color scheme: Deep Blues and Grayish Purples

**Comment by Nick1443** [comment]
![rock](https://user-images.githubusercontent.com/32180567/32080682-ea45ddca-ba65-11e7-944d-5b2f4a821a32.png)

**Comment by Nick1443** [comment]
![rock](https://user-images.githubusercontent.com/32180567/32080714-10f26b96-ba66-11e7-8496-e05e6578712c.png)

**Comment by Nick1443** [comment]
Sorry accidentally closed it for a sec

**Comment by maggie00** [comment]
![boulder prpl](https://user-images.githubusercontent.com/32180561/32198759-b84b340e-bd86-11e7-9612-55026c04d199.png)

**Comment by maggie00** [comment]
![stone prpl](https://user-images.githubusercontent.com/32180561/32199398-9b6e52f0-bd89-11e7-9503-33b6cfb39f99.png)

**Comment by AndrewGalusha** [comment]
![rock3](https://user-images.githubusercontent.com/29155447/32311716-564b13f0-bf57-11e7-9e51-2da234fdd250.png)
Base tile for caves, we can use Magali's pictures as assets that'd be placed on these base tiles

**Comment by maggie00** [comment]
![running water](https://user-images.githubusercontent.com/32180561/32353877-7ea0ea0e-bfe4-11e7-9e24-b49f457a200b.png)
Running water tile

**Comment by AndrewGalusha** [comment]
![ore tile](https://user-images.githubusercontent.com/29155447/32477609-677aeff2-c334-11e7-85fc-f6eaac2476e3.png)
Some sort of ore, kinda like a "wild card" tile

**Comment by AndrewGalusha** [comment]
When we bring all of these tiles together for level 1, we may need to do a little bit of color tone editing to fit all of the art styles together neatly. Just a head's up, if you're good at this sorta thing be ready.

**Comment by AndrewGalusha** [comment]
Any ideas for what else we may need? We have a base tile and multiple "wild tiles" to keep things interesting currently.

**Comment by maggie00** [comment]
![stationary water](https://user-images.githubusercontent.com/32180561/32634006-9ad5dcb4-c55e-11e7-9fab-8331802f871b.png)

**Comment by maggie00** [comment]
![stationary better](https://user-images.githubusercontent.com/32180561/32634050-ca056d2e-c55e-11e7-856b-5d6e252a9680.png)

**Comment by maggie00** [comment]
![stationary better](https://user-images.githubusercontent.com/32180561/32634173-32efc500-c55f-11e7-8043-bd0c58d94884.png)

**Comment by maggie00** [comment]
![turquoise crystal](https://user-images.githubusercontent.com/32180561/32634938-f27dacb8-c562-11e7-9a96-95dec2663993.png)

**Comment by AndrewGalusha** [comment]
![waterimg](https://user-images.githubusercontent.com/29155447/32635157-e5053384-c563-11e7-81dc-73164f56310b.png)
Here's a darker version of the water tile for our cave scenario.

**Comment by SamyGentle52** [comment]
![rock2](https://user-images.githubusercontent.com/32180556/32683027-00f57134-c62d-11e7-854e-a78d2b4a78df.png)

<img width="64" alt="rock3" src="https://user-images.githubusercontent.com/32180556/32683049-2bfc86ba-c62d-11e7-85eb-2d2178fd0451.png">

Cave rocks

**Comment by moonshot-3817** [comment]
<img width="64" alt="ore" src="https://user-images.githubusercontent.com/32180556/32683336-62a65d06-c62f-11e7-8f65-2957e19d7f86.png">
Here is an idea for some silver ore

**Comment by AndrewGalusha** [comment]
We can discuss final tile colors and other things tomorrow at club, for now let's see any other pieces you're able to make.

**Comment by maggie00** [comment]
![cave top](https://user-images.githubusercontent.com/32180561/32913831-6c4e5870-cac8-11e7-9f88-290d46e7766b.png)

**Comment by maggie00** [comment]
![rock tile cool](https://user-images.githubusercontent.com/32180561/32921274-d070c3d8-cae1-11e7-84bc-4389e5f8b925.png)

**Comment by maggie00** [comment]
![rock tile different lighting](https://user-images.githubusercontent.com/32180561/32921823-01a10128-cae4-11e7-9693-fabcbc6c303d.png)
i changed the lighting a little on this one

**Comment by moonshot-3817** [comment]
These will be final tiles:
![rockbase](https://user-images.githubusercontent.com/29155447/32922136-9c0d96f8-cae5-11e7-9730-a23fc9222fb6.png)
![rocks](https://user-images.githubusercontent.com/29155447/32924637-76d41fa8-caf2-11e7-8515-9a50562d09ba.png)
![rockstile](https://user-images.githubusercontent.com/29155447/32923952-27700c22-caef-11e7-834b-cb1c4c8f9191.png)
![tilebasereal](https://user-images.githubusercontent.com/29155447/32924416-635b3dd6-caf1-11e7-86eb-ff38ba9ed37e.png)
![rockyrocks](https://user-images.githubusercontent.com/29155447/32924531-e971be86-caf1-11e7-9dc3-b858c5f37071.png)

Will still need more though...

**Comment by AndrewGalusha** [comment]
Here's an example using some of the tiles we have so far...
![cavelevelex](https://user-images.githubusercontent.com/29155447/32925313-282fd6d6-caf6-11e7-8f18-a0235ab2af4f.png)
...and the best part is that this literally took me like 10 minutes

**Comment by AndrewGalusha** [comment]
Woops, didn't mean to do that

**Comment by AndrewGalusha** [comment]
now all we need is some dynamic lighting...

**Comment by AndrewGalusha** [comment]
![image](https://user-images.githubusercontent.com/29155447/33744611-ea9362f8-db66-11e7-87e3-ccd79a8ed2e0.png)
![image](https://user-images.githubusercontent.com/29155447/33744655-1db0e98a-db67-11e7-95b2-6417cdadd5f2.png)
