### ISSUE TITLE
Sound effects- Grunting (For Speaking)

### ISSUE THREAD

**Issue by KadenFoley** [Tat5ato/Phantasmic-Mind#78]
Just like the sounds that play for each letter "spoken" in RPG text boxes. Undertale is a really good example for these types of sounds

**Comment by AndrewGalusha** [comment]
Here's one for when an electric based being is talking (one tone) https://soundcloud.com/user-440644275/electric-ai-talkinguse-for-game and here's for multiple tones (for what it might sound like in game) https://soundcloud.com/user-440644275/electric-ai-talkingexample-for-what-it-may-sound-like-in-game

**Comment by AndrewGalusha** [comment]
Male voice single tone https://soundcloud.com/user-440644275/male-voiceone-tone and example https://soundcloud.com/user-440644275/malevoiceexample. Also for the female voice, speeding up the audio track isn't quite working so best case scenario we can have any girls that'd be able to do a quick snippet of something that sounds like what I did with the male voice.

**Comment by slendyglowstone** [comment]
Eh.... I cant hear the Voices, though I can hear the electric one
