### ISSUE TITLE
Art for Background/Environment

### ISSUE THREAD

**Issue by Tat5ato** [Tat5ato/Phantasmic-Mind#8]
This is the more demanding task for art since it requires not only understanding of room layout, but also making sure it conveys a particular feeling. Since we need one level to be made, one theme of the room is needed. The particular colors to focus on are part purple and blue, with evergreen (or close to that) strewn about. Also there is at least going to be one room lit with moss so take that into consideration.

**Comment by Nick1443** [comment]
![lovecraft horror pixel art](https://user-images.githubusercontent.com/32180567/31101832-358e24bc-a784-11e7-8c56-15636a5e67bd.png)

**Comment by hecker-man** [comment]
Due on Oct. 23

**Comment by maggie00** [comment]
![cave grounds looking from above](https://user-images.githubusercontent.com/32180561/31916421-8396af6a-b807-11e7-8acb-7483773104ac.png)

**Comment by maggie00** [comment]
![forest grounds drkr](https://user-images.githubusercontent.com/32180561/31916874-973ff65a-b809-11e7-899f-b3bc331bcf3d.png)
