### ISSUE TITLE
Sound for Player Interaction

### ISSUE THREAD

**Issue by Tat5ato** [Tat5ato/Phantasmic-Mind#9]
When I mean interaction, it refers to picking up objects and combat noises; the pick up sound can be akin to something like picking up something in a bag, while the combat noises are grunts, punches, etc.

**Comment by AndrewGalusha** [comment]
Can opening sound, can be played when the player interacts with a soda or something like that in the menu/hotbar. https://soundcloud.com/user-440644275/can-opening-efx
